import type { City, Unit } from "@/lib/game/types";

/**
 * Southern-dialect curriculum seed.
 * Phase 1 ships Unit 0 + Unit 1; Phase 2+ adds Units 2–12.
 */

export const UNITS: Unit[] = [
  {
    id: "u0",
    order: 0,
    title: "Âm Thanh",
    titleEnglish: "Sounds",
    theme: "sounds",
    city: "mekong",
    description: "Meet the 6 written tones (5 spoken in the South), Vietnamese vowels, and your first words.",
    lessons: [
      {
        id: "u0-l1",
        unitId: "u0",
        order: 1,
        title: "Năm Thanh",
        titleEnglish: "The Five Spoken Tones",
        xpReward: 30,
        exercises: [
          {
            id: "u0-l1-e1",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            promptEnglish: "Listen carefully — the tone changes the meaning",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "ma",
            correctTone: "ngang",
          },
          {
            id: "u0-l1-e2",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "má",
            correctTone: "sac",
          },
          {
            id: "u0-l1-e3",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "mà",
            correctTone: "huyen",
          },
          {
            id: "u0-l1-e4",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "mạ",
            correctTone: "nang",
          },
          {
            id: "u0-l1-e5",
            kind: "translate",
            prompt: "Which one means \"mother\" (Southern)?",
            trainsStat: "tuVung",
            direction: "vi-to-en",
            source: "má",
            options: ["ghost", "but", "mother", "tomb"],
            correct: 2,
          },
        ],
      },
      {
        id: "u0-l2",
        unitId: "u0",
        order: 2,
        title: "Bảng Chữ Cái",
        titleEnglish: "The Alphabet",
        xpReward: 30,
        exercises: [
          {
            id: "u0-l2-e1",
            kind: "listen",
            prompt: "Tap the syllable you hear",
            trainsStat: "thinh",
            audioText: "đi",
            options: ["đi", "ti", "thi", "chi"],
            correct: 0,
          },
          {
            id: "u0-l2-e2",
            kind: "listen",
            prompt: "Tap the syllable you hear",
            trainsStat: "thinh",
            audioText: "nghe",
            options: ["nghe", "ne", "nẻ", "ngê"],
            correct: 0,
          },
          {
            id: "u0-l2-e3",
            kind: "listen",
            prompt: "Tap the syllable you hear",
            trainsStat: "thinh",
            audioText: "phở",
            options: ["pho", "phở", "phổ", "pha"],
            correct: 1,
          },
          {
            id: "u0-l2-e4",
            kind: "translate",
            prompt: "Which sound does the letter Đ make?",
            trainsStat: "van",
            direction: "vi-to-en",
            source: "đ",
            options: ["like 'd' in 'do'", "like 'th' in 'this'", "like 'z' in 'zoo'", "like 'y' in 'yes'"],
            correct: 0,
          },
        ],
      },
      {
        id: "u0-l3",
        unitId: "u0",
        order: 3,
        title: "Từ Đầu Tiên",
        titleEnglish: "First Words",
        xpReward: 40,
        exercises: [
          {
            id: "u0-l3-e1",
            kind: "translate",
            prompt: "How do you say \"hello\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "hello",
            options: ["chào", "cảm ơn", "tạm biệt", "xin lỗi"],
            correct: 0,
          },
          {
            id: "u0-l3-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "cảm ơn",
            options: ["cảm ơn", "không", "chào", "xin lỗi"],
            correct: 0,
          },
          {
            id: "u0-l3-e3",
            kind: "translate",
            prompt: "What does \"cảm ơn\" mean?",
            trainsStat: "tuVung",
            direction: "vi-to-en",
            source: "cảm ơn",
            options: ["sorry", "hello", "thank you", "goodbye"],
            correct: 2,
          },
          {
            id: "u0-l3-e4",
            kind: "tone-match",
            prompt: "What tone is on \"chào\"?",
            trainsStat: "thanhDieu",
            baseSyllable: "chao",
            audioText: "chào",
            correctTone: "huyen",
          },
          {
            id: "u0-l3-e5",
            kind: "translate",
            prompt: "How do you say \"goodbye\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "goodbye",
            options: ["xin chào", "tạm biệt", "không sao", "cảm ơn"],
            correct: 1,
          },
          {
            id: "u0-l3-e6",
            kind: "pair-match",
            prompt: "Pair the greetings",
            trainsStat: "tuVung",
            pairs: [
              { left: "chào", right: "hello", audioText: "chào" },
              { left: "tạm biệt", right: "goodbye", audioText: "tạm biệt" },
              { left: "cảm ơn", right: "thank you", audioText: "cảm ơn" },
              { left: "xin lỗi", right: "sorry", audioText: "xin lỗi" },
            ],
          },
          {
            id: "u0-l3-e7",
            kind: "fill-blank",
            prompt: "Complete the polite hello",
            trainsStat: "nguPhap",
            sentence: "___ chào",
            options: ["xin", "tôi", "bạn", "ơn"],
            correct: 0,
            audioText: "xin chào",
            englishHint: "Polite \"hello\" — adds respect for someone you don't know",
          },
        ],
      },
    ],
  },
  {
    id: "u1",
    order: 1,
    title: "Xin Chào",
    titleEnglish: "Greetings",
    theme: "greetings",
    city: "saigon",
    description: "Greet, introduce yourself, and meet someone in Sài Gòn.",
    lessons: [
      {
        id: "u1-l1",
        unitId: "u1",
        order: 1,
        title: "Chào Hỏi",
        titleEnglish: "Saying Hello",
        xpReward: 40,
        exercises: [
          {
            id: "u1-l1-e1",
            kind: "translate",
            prompt: "How do you say \"hello\" politely (to someone older)?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "hello (polite)",
            options: ["chào bạn", "xin chào", "ê", "ơi"],
            correct: 1,
          },
          {
            id: "u1-l1-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "xin chào",
            options: ["xin chào", "cảm ơn", "tạm biệt", "không sao"],
            correct: 0,
          },
          {
            id: "u1-l1-e3",
            kind: "translate",
            prompt: "What does \"chào em\" mean?",
            trainsStat: "tuVung",
            promptEnglish: "Em = younger person",
            direction: "vi-to-en",
            source: "chào em",
            options: ["hi (to younger person)", "thank you younger sibling", "see you later", "good morning"],
            correct: 0,
          },
          {
            id: "u1-l1-e4",
            kind: "tone-match",
            prompt: "Tap the tone on \"chào\"",
            trainsStat: "thanhDieu",
            baseSyllable: "chao",
            audioText: "chào",
            correctTone: "huyen",
          },
          {
            id: "u1-l1-e5",
            kind: "speak",
            prompt: "Now you say it: \"chào\"",
            promptEnglish: "Falling (huyền) tone — start high, glide down",
            trainsStat: "khau",
            targetText: "chào",
            targetTone: "huyen",
            audioText: "chào",
            dialectMerged: false,
          },
          {
            id: "u1-l1-e6",
            kind: "speak",
            prompt: "Say \"tạm biệt\" — \"goodbye\"",
            promptEnglish: "Heavy (nặng) tone on tạm — drop low and stop",
            trainsStat: "khau",
            targetText: "tạm biệt",
            targetTone: "nang",
            audioText: "tạm biệt",
            dialectMerged: false,
          },
        ],
      },
      {
        id: "u1-l2",
        unitId: "u1",
        order: 2,
        title: "Tên Của Bạn",
        titleEnglish: "Your Name",
        xpReward: 40,
        exercises: [
          {
            id: "u1-l2-e1",
            kind: "translate",
            prompt: "How do you ask \"What's your name?\" (to a friend)",
            trainsStat: "nguPhap",
            direction: "en-to-vi",
            source: "what's your name?",
            options: ["bạn tên gì?", "tôi là ai?", "bạn ở đâu?", "bao nhiêu tuổi?"],
            correct: 0,
          },
          {
            id: "u1-l2-e2",
            kind: "translate",
            prompt: "Translate: \"My name is Mai\"",
            trainsStat: "but",
            direction: "en-to-vi",
            source: "my name is Mai",
            options: ["tôi tên Mai", "bạn tên Mai", "Mai là tôi", "tôi là Mai gì"],
            correct: 0,
          },
          {
            id: "u1-l2-e3",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "tôi tên là Nam",
            options: ["tôi tên là Nam", "tôi tên là Nga", "tôi tên là Lan", "tôi tên là Hà"],
            correct: 0,
          },
          {
            id: "u1-l2-e4",
            kind: "translate",
            prompt: "What does \"tên\" mean?",
            trainsStat: "tuVung",
            direction: "vi-to-en",
            source: "tên",
            options: ["age", "name", "home", "you"],
            correct: 1,
          },
          {
            id: "u1-l2-e5",
            kind: "speak",
            prompt: "Say \"tôi\" — \"I\"",
            promptEnglish: "Level (ngang) tone — flat, no glide",
            trainsStat: "khau",
            targetText: "tôi",
            targetTone: "ngang",
            audioText: "tôi",
            dialectMerged: false,
          },
          {
            id: "u1-l2-e6",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Bạn ___ gì?",
            options: ["tên", "là", "rất", "ơn"],
            correct: 0,
            audioText: "Bạn tên gì?",
            englishHint: "What is your name? (casual)",
          },
        ],
      },
      {
        id: "u1-l3",
        unitId: "u1",
        order: 3,
        title: "Lịch Sự",
        titleEnglish: "Politeness",
        xpReward: 50,
        exercises: [
          {
            id: "u1-l3-e1",
            kind: "translate",
            prompt: "How do you say \"thank you\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "thank you",
            options: ["xin lỗi", "cảm ơn", "không có gì", "vui lòng"],
            correct: 1,
          },
          {
            id: "u1-l3-e2",
            kind: "translate",
            prompt: "How do you say \"sorry\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "sorry",
            options: ["cảm ơn", "xin chào", "xin lỗi", "không sao"],
            correct: 2,
          },
          {
            id: "u1-l3-e3",
            kind: "translate",
            prompt: "What does \"không có gì\" mean?",
            trainsStat: "tuVung",
            promptEnglish: "Common reply",
            direction: "vi-to-en",
            source: "không có gì",
            options: ["I don't know", "you're welcome / no problem", "I'm sorry", "see you later"],
            correct: 1,
          },
          {
            id: "u1-l3-e4",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "rất vui được gặp bạn",
            options: ["rất vui được gặp bạn", "tôi không biết bạn", "hẹn gặp lại bạn", "cảm ơn nhiều bạn"],
            correct: 0,
          },
          {
            id: "u1-l3-e5",
            kind: "translate",
            prompt: "Translate: \"Nice to meet you\"",
            trainsStat: "but",
            direction: "en-to-vi",
            source: "nice to meet you",
            options: ["chào tạm biệt", "rất vui được gặp bạn", "cảm ơn rất nhiều", "xin lỗi nhiều"],
            correct: 1,
          },
          {
            id: "u1-l3-e6",
            kind: "speak",
            prompt: "Say \"cảm ơn\" — \"thank you\"",
            promptEnglish: "Dipping (hỏi) tone on cảm",
            trainsStat: "khau",
            targetText: "cảm ơn",
            targetTone: "hoi",
            audioText: "cảm ơn",
            dialectMerged: true,
          },
          {
            id: "u1-l3-e7",
            kind: "speak",
            prompt: "Say \"xin lỗi\" — \"sorry\"",
            promptEnglish: "Lỗi merges with hỏi in Southern speech",
            trainsStat: "khau",
            targetText: "xin lỗi",
            targetTone: "nga",
            audioText: "xin lỗi",
            dialectMerged: true,
          },
          {
            id: "u1-l3-e8",
            kind: "pair-match",
            prompt: "Pair these polite phrases",
            trainsStat: "tuVung",
            pairs: [
              { left: "cảm ơn", right: "thank you", audioText: "cảm ơn" },
              { left: "xin lỗi", right: "sorry", audioText: "xin lỗi" },
              { left: "không có gì", right: "you're welcome", audioText: "không có gì" },
              { left: "không sao", right: "no problem", audioText: "không sao" },
            ],
          },
          {
            id: "u1-l3-e9",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Rất vui được ___ bạn",
            options: ["gặp", "tên", "đi", "chào"],
            correct: 0,
            audioText: "Rất vui được gặp bạn",
            englishHint: "Nice to meet you",
          },
          {
            id: "u1-l3-e10",
            kind: "story",
            prompt: "At a café in Sài Gòn",
            promptEnglish: "Meet someone new — pick the right Vietnamese reply",
            trainsStat: "tuVung",
            startId: "n1",
            nodes: [
              {
                id: "n1",
                kind: "line",
                speaker: "narrator",
                text: "A friendly stranger walks up to your table and smiles.",
                next: "n2",
              },
              {
                id: "n2",
                kind: "line",
                speaker: "Mai",
                text: "Xin chào! Tôi tên Mai.",
                textEnglish: "Hello! My name is Mai.",
                audioText: "Xin chào! Tôi tên Mai.",
                next: "c1",
              },
              {
                id: "c1",
                kind: "choice",
                prompt: "Reply with your name — say you're Nam:",
                options: [
                  { text: "Tôi tên Nam.", textEnglish: "My name is Nam.", correct: true, next: "n3" },
                  { text: "Cảm ơn.", textEnglish: "Thank you.", correct: false, next: "n3-fix" },
                  { text: "Tạm biệt.", textEnglish: "Goodbye.", correct: false, next: "n3-fix" },
                ],
              },
              {
                id: "n3-fix",
                kind: "line",
                speaker: "Mai",
                text: "Hmm? Tên bạn là gì?",
                textEnglish: "Hmm? What's your name?",
                audioText: "Tên bạn là gì?",
                next: "n3",
              },
              {
                id: "n3",
                kind: "line",
                speaker: "Mai",
                text: "Rất vui được gặp bạn!",
                textEnglish: "Nice to meet you!",
                audioText: "Rất vui được gặp bạn!",
                next: "c2",
              },
              {
                id: "c2",
                kind: "choice",
                prompt: "Reply politely:",
                options: [
                  {
                    text: "Rất vui được gặp bạn.",
                    textEnglish: "Nice to meet you too.",
                    correct: true,
                    next: "end-good",
                  },
                  { text: "Không sao.", textEnglish: "No problem.", correct: false, next: "end-meh" },
                ],
              },
              {
                id: "end-good",
                kind: "end",
                text: "You made a friend in Sài Gòn.",
                textEnglish: "Smooth introduction — Mai walks off humming.",
              },
              {
                id: "end-meh",
                kind: "end",
                text: "Mai gives a polite smile and turns back to her phone.",
                textEnglish: "Try the conversation again to nail it.",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u2",
    order: 2,
    title: "Tâm Tình",
    titleEnglish: "Heart & Weather",
    theme: "feelings-weather",
    city: "dalat",
    description: "In the cool mountain air of Đà Lạt, learn to ask how people are, talk about weather, count to ten, and order at a café.",
    lessons: [
      {
        id: "u2-l1",
        unitId: "u2",
        order: 1,
        title: "Bạn Khỏe Không?",
        titleEnglish: "How Are You?",
        xpReward: 40,
        exercises: [
          {
            id: "u2-l1-e1",
            kind: "translate",
            prompt: "How do you ask \"How are you?\"",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "how are you?",
            options: ["bạn khỏe không?", "bạn tên gì?", "bạn ở đâu?", "rất vui được gặp"],
            correct: 0,
          },
          {
            id: "u2-l1-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "tôi khỏe",
            options: ["tôi khỏe", "tôi mệt", "tôi vui", "tôi buồn"],
            correct: 0,
          },
          {
            id: "u2-l1-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"khỏe\"",
            trainsStat: "thanhDieu",
            baseSyllable: "khoe",
            audioText: "khỏe",
            correctTone: "hoi",
          },
          {
            id: "u2-l1-e4",
            kind: "speak",
            prompt: "Say \"khỏe\" — \"well / healthy\"",
            promptEnglish: "Dipping (hỏi) tone — dip down then come back up",
            trainsStat: "khau",
            targetText: "khỏe",
            targetTone: "hoi",
            audioText: "khỏe",
            dialectMerged: true,
          },
          {
            id: "u2-l1-e5",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Tôi rất ___",
            options: ["khỏe", "vui", "mệt", "buồn"],
            correct: 0,
            audioText: "Tôi rất khỏe",
            englishHint: "I'm very well",
          },
        ],
      },
      {
        id: "u2-l2",
        unitId: "u2",
        order: 2,
        title: "Thời Tiết",
        titleEnglish: "Weather",
        xpReward: 40,
        exercises: [
          {
            id: "u2-l2-e1",
            kind: "translate",
            prompt: "How do you say \"cold\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "cold",
            options: ["lạnh", "nóng", "mưa", "nắng"],
            correct: 0,
          },
          {
            id: "u2-l2-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Trời lạnh",
            options: ["Trời lạnh", "Trời nóng", "Trời mưa", "Trời nắng"],
            correct: 0,
          },
          {
            id: "u2-l2-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"nắng\"",
            trainsStat: "thanhDieu",
            baseSyllable: "nang",
            audioText: "nắng",
            correctTone: "sac",
          },
          {
            id: "u2-l2-e4",
            kind: "speak",
            prompt: "Say \"mưa\" — \"rain\"",
            promptEnglish: "Level (ngang) tone — flat, no glide",
            trainsStat: "khau",
            targetText: "mưa",
            targetTone: "ngang",
            audioText: "mưa",
            dialectMerged: false,
          },
          {
            id: "u2-l2-e5",
            kind: "pair-match",
            prompt: "Pair the weather words",
            trainsStat: "tuVung",
            pairs: [
              { left: "lạnh", right: "cold", audioText: "lạnh" },
              { left: "nóng", right: "hot", audioText: "nóng" },
              { left: "mưa", right: "rain", audioText: "mưa" },
              { left: "nắng", right: "sunny", audioText: "nắng" },
            ],
          },
        ],
      },
      {
        id: "u2-l3",
        unitId: "u2",
        order: 3,
        title: "Số Đếm",
        titleEnglish: "Counting 1-10",
        xpReward: 40,
        exercises: [
          {
            id: "u2-l3-e1",
            kind: "translate",
            prompt: "How do you say \"five\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "five",
            options: ["năm", "ba", "bốn", "sáu"],
            correct: 0,
          },
          {
            id: "u2-l3-e2",
            kind: "listen",
            prompt: "Tap the number you hear",
            trainsStat: "thinh",
            audioText: "ba",
            options: ["ba", "hai", "năm", "bốn"],
            correct: 0,
          },
          {
            id: "u2-l3-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"bốn\"",
            trainsStat: "thanhDieu",
            baseSyllable: "bon",
            audioText: "bốn",
            correctTone: "sac",
          },
          {
            id: "u2-l3-e4",
            kind: "speak",
            prompt: "Say \"một\" — \"one\"",
            promptEnglish: "Heavy (nặng) tone — drop low and stop",
            trainsStat: "khau",
            targetText: "một",
            targetTone: "nang",
            audioText: "một",
            dialectMerged: false,
          },
          {
            id: "u2-l3-e5",
            kind: "pair-match",
            prompt: "Pair the numbers",
            trainsStat: "tuVung",
            pairs: [
              { left: "một", right: "1", audioText: "một" },
              { left: "hai", right: "2", audioText: "hai" },
              { left: "ba", right: "3", audioText: "ba" },
              { left: "bốn", right: "4", audioText: "bốn" },
            ],
          },
        ],
      },
      {
        id: "u2-l4",
        unitId: "u2",
        order: 4,
        title: "Cà Phê Đà Lạt",
        titleEnglish: "Coffee at Đà Lạt",
        xpReward: 60,
        exercises: [
          {
            id: "u2-l4-e1",
            kind: "translate",
            prompt: "How do you say \"coffee\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "coffee",
            options: ["cà phê", "trà", "nước", "cơm"],
            correct: 0,
          },
          {
            id: "u2-l4-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Cho tôi một ly cà phê",
            options: ["Cho tôi một ly cà phê", "Cho tôi một ly trà", "Cho tôi một ly nước", "Cảm ơn nhiều"],
            correct: 0,
          },
          {
            id: "u2-l4-e3",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Cho tôi ___ ly trà",
            options: ["một", "hai", "ba", "bốn"],
            correct: 0,
            audioText: "Cho tôi một ly trà",
            englishHint: "Give me one cup of tea",
          },
          {
            id: "u2-l4-e4",
            kind: "speak",
            prompt: "Say \"cà phê\" — \"coffee\"",
            promptEnglish: "Falling (huyền) tone on cà",
            trainsStat: "khau",
            targetText: "cà phê",
            targetTone: "huyen",
            audioText: "cà phê",
            dialectMerged: false,
          },
          {
            id: "u2-l4-e5",
            kind: "story",
            prompt: "At a café in Đà Lạt",
            promptEnglish: "Order coffee in the cool mountain mist",
            trainsStat: "tuVung",
            startId: "n1",
            nodes: [
              {
                id: "n1",
                kind: "line",
                speaker: "narrator",
                text: "The Đà Lạt mist rolls past the windows. A friendly barista turns to you.",
                next: "n2",
              },
              {
                id: "n2",
                kind: "line",
                speaker: "Linh",
                text: "Chào bạn. Bạn muốn gì?",
                textEnglish: "Hi there. What would you like?",
                audioText: "Chào bạn. Bạn muốn gì?",
                next: "c1",
              },
              {
                id: "c1",
                kind: "choice",
                prompt: "Order a coffee:",
                options: [
                  { text: "Cho tôi một ly cà phê.", textEnglish: "Give me one cup of coffee.", correct: true, next: "n3" },
                  { text: "Tôi không biết.", textEnglish: "I don't know.", correct: false, next: "n3-fix" },
                  { text: "Cảm ơn.", textEnglish: "Thank you.", correct: false, next: "n3-fix" },
                ],
              },
              {
                id: "n3-fix",
                kind: "line",
                speaker: "Linh",
                text: "À? Bạn muốn uống gì?",
                textEnglish: "Hmm? What would you like to drink?",
                audioText: "Bạn muốn uống gì?",
                next: "n3",
              },
              {
                id: "n3",
                kind: "line",
                speaker: "Linh",
                text: "Dạ. Một ly cà phê.",
                textEnglish: "Yes. One cup of coffee.",
                audioText: "Dạ. Một ly cà phê.",
                next: "c2",
              },
              {
                id: "c2",
                kind: "choice",
                prompt: "Reply politely:",
                options: [
                  { text: "Cảm ơn nhiều.", textEnglish: "Thank you very much.", correct: true, next: "end-good" },
                  { text: "Không sao.", textEnglish: "No problem.", correct: false, next: "end-meh" },
                ],
              },
              {
                id: "end-good",
                kind: "end",
                text: "You sip the warm coffee, watching the Đà Lạt mist roll in.",
                textEnglish: "Smooth order — Linh smiles and sets the cup down.",
              },
              {
                id: "end-meh",
                kind: "end",
                text: "Awkward silence. The coffee gets cold while you both look elsewhere.",
                textEnglish: "Try again — \"cảm ơn\" is the natural reply.",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u3",
    order: 3,
    title: "Đi Chợ Hội An",
    titleEnglish: "Hội An Market",
    theme: "market-food",
    city: "hoian",
    description: "Wander the lantern-lit streets of Hội An. Learn market vocabulary, food words, and how to ask the price.",
    lessons: [
      {
        id: "u3-l1",
        unitId: "u3",
        order: 1,
        title: "Đi Chợ",
        titleEnglish: "Going to Market",
        xpReward: 40,
        exercises: [
          {
            id: "u3-l1-e1",
            kind: "translate",
            prompt: "How do you say \"market\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "market",
            options: ["chợ", "phố", "nhà", "đường"],
            correct: 0,
          },
          {
            id: "u3-l1-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Tôi đi chợ",
            options: ["Tôi đi chợ", "Tôi đi học", "Tôi đi làm", "Tôi đi chơi"],
            correct: 0,
          },
          {
            id: "u3-l1-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"chợ\"",
            trainsStat: "thanhDieu",
            baseSyllable: "cho",
            audioText: "chợ",
            correctTone: "nang",
          },
          {
            id: "u3-l1-e4",
            kind: "speak",
            prompt: "Say \"mua\" — \"to buy\"",
            promptEnglish: "Level (ngang) tone — flat",
            trainsStat: "khau",
            targetText: "mua",
            targetTone: "ngang",
            audioText: "mua",
            dialectMerged: false,
          },
          {
            id: "u3-l1-e5",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Tôi ___ chợ",
            options: ["đi", "ăn", "mua", "uống"],
            correct: 0,
            audioText: "Tôi đi chợ",
            englishHint: "I'm going to the market",
          },
        ],
      },
      {
        id: "u3-l2",
        unitId: "u3",
        order: 2,
        title: "Món Ăn",
        titleEnglish: "Food",
        xpReward: 40,
        exercises: [
          {
            id: "u3-l2-e1",
            kind: "translate",
            prompt: "How do you say \"rice\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "rice (cooked)",
            options: ["cơm", "phở", "bún", "mì"],
            correct: 0,
          },
          {
            id: "u3-l2-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "phở",
            options: ["phở", "cơm", "bún", "mì"],
            correct: 0,
          },
          {
            id: "u3-l2-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"phở\"",
            trainsStat: "thanhDieu",
            baseSyllable: "pho",
            audioText: "phở",
            correctTone: "hoi",
          },
          {
            id: "u3-l2-e4",
            kind: "speak",
            prompt: "Say \"ngon\" — \"delicious\"",
            promptEnglish: "Level (ngang) tone — flat",
            trainsStat: "khau",
            targetText: "ngon",
            targetTone: "ngang",
            audioText: "ngon",
            dialectMerged: false,
          },
          {
            id: "u3-l2-e5",
            kind: "pair-match",
            prompt: "Pair the foods",
            trainsStat: "tuVung",
            pairs: [
              { left: "cơm", right: "rice", audioText: "cơm" },
              { left: "phở", right: "noodle soup", audioText: "phở" },
              { left: "bún", right: "vermicelli", audioText: "bún" },
              { left: "mì", right: "noodles", audioText: "mì" },
            ],
          },
        ],
      },
      {
        id: "u3-l3",
        unitId: "u3",
        order: 3,
        title: "Bao Nhiêu?",
        titleEnglish: "How Much?",
        xpReward: 40,
        exercises: [
          {
            id: "u3-l3-e1",
            kind: "translate",
            prompt: "How do you ask \"how much?\"",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "how much?",
            options: ["bao nhiêu?", "bạn tên gì?", "ở đâu?", "khi nào?"],
            correct: 0,
          },
          {
            id: "u3-l3-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Cái này bao nhiêu?",
            options: ["Cái này bao nhiêu?", "Cái kia bao nhiêu?", "Bạn tên gì?", "Cái này đẹp"],
            correct: 0,
          },
          {
            id: "u3-l3-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"tiền\"",
            trainsStat: "thanhDieu",
            baseSyllable: "tien",
            audioText: "tiền",
            correctTone: "huyen",
          },
          {
            id: "u3-l3-e4",
            kind: "speak",
            prompt: "Say \"đắt\" — \"expensive\"",
            promptEnglish: "Rising (sắc) tone — pitch goes up",
            trainsStat: "khau",
            targetText: "đắt",
            targetTone: "sac",
            audioText: "đắt",
            dialectMerged: false,
          },
          {
            id: "u3-l3-e5",
            kind: "pair-match",
            prompt: "Pair the market words",
            trainsStat: "tuVung",
            pairs: [
              { left: "bao nhiêu", right: "how much", audioText: "bao nhiêu" },
              { left: "tiền", right: "money", audioText: "tiền" },
              { left: "đắt", right: "expensive", audioText: "đắt" },
              { left: "rẻ", right: "cheap", audioText: "rẻ" },
            ],
          },
        ],
      },
      {
        id: "u3-l4",
        unitId: "u3",
        order: 4,
        title: "Đêm Hội An",
        titleEnglish: "Hội An Night",
        xpReward: 60,
        exercises: [
          {
            id: "u3-l4-e1",
            kind: "translate",
            prompt: "How do you say \"lantern\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "lantern",
            options: ["đèn lồng", "đèn pin", "ánh sáng", "bóng đèn"],
            correct: 0,
          },
          {
            id: "u3-l4-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Cái này đẹp lắm",
            options: ["Cái này đẹp lắm", "Cái này đắt lắm", "Cái kia đẹp lắm", "Cái này rẻ lắm"],
            correct: 0,
          },
          {
            id: "u3-l4-e3",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Cái này bao nhiêu ___?",
            options: ["tiền", "ngon", "đẹp", "lắm"],
            correct: 0,
            audioText: "Cái này bao nhiêu tiền?",
            englishHint: "How much money is this?",
          },
          {
            id: "u3-l4-e4",
            kind: "speak",
            prompt: "Say \"rẻ\" — \"cheap\"",
            promptEnglish: "Dipping (hỏi) tone — dip down then come back",
            trainsStat: "khau",
            targetText: "rẻ",
            targetTone: "hoi",
            audioText: "rẻ",
            dialectMerged: true,
          },
          {
            id: "u3-l4-e5",
            kind: "story",
            prompt: "At a Hội An lantern stall",
            promptEnglish: "Bargain politely with the vendor",
            trainsStat: "tuVung",
            startId: "n1",
            nodes: [
              {
                id: "n1",
                kind: "line",
                speaker: "narrator",
                text: "Lanterns glow in every color along the Hội An riverside. A vendor smiles as you stop at her stall.",
                next: "n2",
              },
              {
                id: "n2",
                kind: "line",
                speaker: "Hoa",
                text: "Chào bạn! Cái đèn lồng này đẹp lắm.",
                textEnglish: "Hi! This lantern is very beautiful.",
                audioText: "Chào bạn! Cái đèn lồng này đẹp lắm.",
                next: "c1",
              },
              {
                id: "c1",
                kind: "choice",
                prompt: "Ask the price:",
                options: [
                  { text: "Cái này bao nhiêu?", textEnglish: "How much is this?", correct: true, next: "n3" },
                  { text: "Tôi không biết.", textEnglish: "I don't know.", correct: false, next: "n3-fix" },
                  { text: "Cảm ơn.", textEnglish: "Thank you.", correct: false, next: "n3-fix" },
                ],
              },
              {
                id: "n3-fix",
                kind: "line",
                speaker: "Hoa",
                text: "À? Bạn muốn hỏi gì?",
                textEnglish: "Hmm? What do you want to ask?",
                audioText: "Bạn muốn hỏi gì?",
                next: "n3",
              },
              {
                id: "n3",
                kind: "line",
                speaker: "Hoa",
                text: "Mười ngàn đồng.",
                textEnglish: "Ten thousand dong.",
                audioText: "Mười ngàn đồng.",
                next: "c2",
              },
              {
                id: "c2",
                kind: "choice",
                prompt: "Reply:",
                options: [
                  { text: "Cảm ơn, tôi mua.", textEnglish: "Thanks, I'll buy it.", correct: true, next: "end-good" },
                  { text: "Đắt quá. Năm ngàn nhé?", textEnglish: "Too expensive. Five thousand, OK?", correct: true, next: "end-bargain" },
                  { text: "Tạm biệt.", textEnglish: "Goodbye.", correct: false, next: "end-meh" },
                ],
              },
              {
                id: "end-good",
                kind: "end",
                text: "Hoa lights the lantern and presses it into your hands.",
                textEnglish: "A clean buy — the lantern glows warm against your palm.",
              },
              {
                id: "end-bargain",
                kind: "end",
                text: "Hoa laughs and meets you at bảy ngàn (7,000). Lantern in hand, you wander on.",
                textEnglish: "Bargain landed — confident moves earn the local price.",
              },
              {
                id: "end-meh",
                kind: "end",
                text: "Hoa shrugs and turns to the next traveler. The lanterns keep glowing without you.",
                textEnglish: "Try again — at least ask the price first.",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u4",
    order: 4,
    title: "Cầu Rồng",
    titleEnglish: "Dragon Bridge",
    theme: "beach-colors-time",
    city: "danang",
    description: "Coastal Đà Nẵng under the sun and the bridge under the stars. Beach vocabulary, colors, times of day, and an evening at the famous Dragon Bridge.",
    lessons: [
      {
        id: "u4-l1",
        unitId: "u4",
        order: 1,
        title: "Đi Biển",
        titleEnglish: "Going to the Beach",
        xpReward: 40,
        exercises: [
          {
            id: "u4-l1-e1",
            kind: "translate",
            prompt: "How do you say \"sea / beach\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "sea / beach",
            options: ["biển", "sông", "núi", "phố"],
            correct: 0,
          },
          {
            id: "u4-l1-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Tôi đi biển",
            options: ["Tôi đi biển", "Tôi đi chợ", "Tôi đi học", "Tôi đi làm"],
            correct: 0,
          },
          {
            id: "u4-l1-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"biển\"",
            trainsStat: "thanhDieu",
            baseSyllable: "bien",
            audioText: "biển",
            correctTone: "hoi",
          },
          {
            id: "u4-l1-e4",
            kind: "speak",
            prompt: "Say \"biển\" — \"sea\"",
            promptEnglish: "Dipping (hỏi) tone — dip down then come back",
            trainsStat: "khau",
            targetText: "biển",
            targetTone: "hoi",
            audioText: "biển",
            dialectMerged: true,
          },
          {
            id: "u4-l1-e5",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Tôi đi ___",
            options: ["biển", "ăn", "học", "mua"],
            correct: 0,
            audioText: "Tôi đi biển",
            englishHint: "I'm going to the beach",
          },
        ],
      },
      {
        id: "u4-l2",
        unitId: "u4",
        order: 2,
        title: "Màu Sắc",
        titleEnglish: "Colors",
        xpReward: 40,
        tips: {
          grammar: [
            {
              pattern: "Noun + màu + Color",
              meaning:
                "In Vietnamese, the color word follows the noun. \"hoa màu đỏ\" literally reads as \"flower color red.\"",
              example: "hoa màu đỏ — a red flower",
            },
          ],
        },
        exercises: [
          {
            id: "u4-l2-e1",
            kind: "translate",
            prompt: "How do you say \"red\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "red",
            options: ["đỏ", "xanh", "vàng", "trắng"],
            correct: 0,
          },
          {
            id: "u4-l2-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "màu xanh",
            options: ["màu xanh", "màu đỏ", "màu vàng", "màu trắng"],
            correct: 0,
          },
          {
            id: "u4-l2-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"vàng\"",
            trainsStat: "thanhDieu",
            baseSyllable: "vang",
            audioText: "vàng",
            correctTone: "huyen",
          },
          {
            id: "u4-l2-e4",
            kind: "speak",
            prompt: "Say \"đỏ\" — \"red\"",
            promptEnglish: "Dipping (hỏi) tone",
            trainsStat: "khau",
            targetText: "đỏ",
            targetTone: "hoi",
            audioText: "đỏ",
            dialectMerged: true,
          },
          {
            id: "u4-l2-e5",
            kind: "pair-match",
            prompt: "Pair the colors",
            trainsStat: "tuVung",
            pairs: [
              { left: "đỏ", right: "red", audioText: "đỏ" },
              { left: "xanh", right: "blue / green", audioText: "xanh" },
              { left: "vàng", right: "yellow", audioText: "vàng" },
              { left: "trắng", right: "white", audioText: "trắng" },
            ],
          },
        ],
      },
      {
        id: "u4-l3",
        unitId: "u4",
        order: 3,
        title: "Buổi Sáng",
        titleEnglish: "Times of Day",
        xpReward: 40,
        exercises: [
          {
            id: "u4-l3-e1",
            kind: "translate",
            prompt: "How do you say \"morning\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "morning",
            options: ["buổi sáng", "buổi trưa", "buổi chiều", "buổi tối"],
            correct: 0,
          },
          {
            id: "u4-l3-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "buổi tối",
            options: ["buổi tối", "buổi sáng", "buổi trưa", "buổi chiều"],
            correct: 0,
          },
          {
            id: "u4-l3-e3",
            kind: "tone-match",
            prompt: "Tap the tone on \"tối\"",
            trainsStat: "thanhDieu",
            baseSyllable: "toi",
            audioText: "tối",
            correctTone: "sac",
          },
          {
            id: "u4-l3-e4",
            kind: "speak",
            prompt: "Say \"chiều\" — \"afternoon\"",
            promptEnglish: "Falling (huyền) tone",
            trainsStat: "khau",
            targetText: "chiều",
            targetTone: "huyen",
            audioText: "chiều",
            dialectMerged: false,
          },
          {
            id: "u4-l3-e5",
            kind: "pair-match",
            prompt: "Pair the times of day",
            trainsStat: "tuVung",
            pairs: [
              { left: "sáng", right: "morning", audioText: "sáng" },
              { left: "trưa", right: "noon", audioText: "trưa" },
              { left: "chiều", right: "afternoon", audioText: "chiều" },
              { left: "tối", right: "evening", audioText: "tối" },
            ],
          },
        ],
      },
      {
        id: "u4-l4",
        unitId: "u4",
        order: 4,
        title: "Cầu Rồng",
        titleEnglish: "Dragon Bridge",
        xpReward: 60,
        exercises: [
          {
            id: "u4-l4-e1",
            kind: "translate",
            prompt: "How do you say \"bridge\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "bridge",
            options: ["cầu", "đường", "phố", "nhà"],
            correct: 0,
          },
          {
            id: "u4-l4-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "Cầu Rồng đẹp lắm",
            options: ["Cầu Rồng đẹp lắm", "Cầu Rồng to lắm", "Đà Nẵng đẹp lắm", "Biển đẹp lắm"],
            correct: 0,
          },
          {
            id: "u4-l4-e3",
            kind: "fill-blank",
            prompt: "Fill the blank",
            trainsStat: "nguPhap",
            sentence: "Cầu Rồng ___ lắm",
            options: ["đẹp", "ngon", "đắt", "rẻ"],
            correct: 0,
            audioText: "Cầu Rồng đẹp lắm",
            englishHint: "Dragon Bridge is very beautiful",
          },
          {
            id: "u4-l4-e4",
            kind: "speak",
            prompt: "Say \"rồng\" — \"dragon\"",
            promptEnglish: "Falling (huyền) tone on rồng",
            trainsStat: "khau",
            targetText: "rồng",
            targetTone: "huyen",
            audioText: "rồng",
            dialectMerged: false,
          },
          {
            id: "u4-l4-e5",
            kind: "story",
            prompt: "An evening at Dragon Bridge",
            promptEnglish: "Meet a friend at the Đà Nẵng riverside",
            trainsStat: "tuVung",
            startId: "n1",
            nodes: [
              {
                id: "n1",
                kind: "line",
                speaker: "narrator",
                text: "It's dusk in Đà Nẵng. Red and yellow lights pulse along Cầu Rồng. Your friend An waves you over to the riverside.",
                next: "n2",
              },
              {
                id: "n2",
                kind: "line",
                speaker: "An",
                text: "Chào bạn! Cầu Rồng đẹp lắm.",
                textEnglish: "Hi! Dragon Bridge is very beautiful.",
                audioText: "Chào bạn! Cầu Rồng đẹp lắm.",
                next: "c1",
              },
              {
                id: "c1",
                kind: "choice",
                prompt: "Agree with An:",
                options: [
                  { text: "Đẹp lắm!", textEnglish: "Very beautiful!", correct: true, next: "n3" },
                  { text: "Tôi không biết.", textEnglish: "I don't know.", correct: false, next: "n3-fix" },
                  { text: "Tạm biệt.", textEnglish: "Goodbye.", correct: false, next: "n3-fix" },
                ],
              },
              {
                id: "n3-fix",
                kind: "line",
                speaker: "An",
                text: "Bạn xem này — đẹp lắm!",
                textEnglish: "Look at this — it's beautiful!",
                audioText: "Bạn xem này. Đẹp lắm.",
                next: "n3",
              },
              {
                id: "n3",
                kind: "line",
                speaker: "An",
                text: "Bạn muốn ăn gì?",
                textEnglish: "What do you want to eat?",
                audioText: "Bạn muốn ăn gì?",
                next: "c2",
              },
              {
                id: "c2",
                kind: "choice",
                prompt: "Order something:",
                options: [
                  { text: "Tôi muốn cà phê.", textEnglish: "I'd like coffee.", correct: true, next: "end-good" },
                  { text: "Tôi muốn phở.", textEnglish: "I'd like phở.", correct: true, next: "end-good-pho" },
                  { text: "Cảm ơn, không.", textEnglish: "Thanks, no.", correct: false, next: "end-meh" },
                ],
              },
              {
                id: "end-good",
                kind: "end",
                text: "You sip cà phê by the bridge as the dragon roars its red-and-yellow fire.",
                textEnglish: "Smooth evening — An grins and points toward the next show.",
              },
              {
                id: "end-good-pho",
                kind: "end",
                text: "Steam rises from the bowl of phở. The dragon breathes its fire and the river glitters.",
                textEnglish: "Phở by the bridge — a Đà Nẵng classic.",
              },
              {
                id: "end-meh",
                kind: "end",
                text: "An shrugs. The dragon roars alone over the river.",
                textEnglish: "Try again — \"Tôi muốn ___\" is a useful pattern.",
              },
            ],
          },
        ],
      },
    ],
  },
];

/** 9 cities along the South-to-North journey, with SVG positions on a stylized Vietnam map. */
export const CITIES: City[] = [
  { id: "mekong",   name: "Đồng Bằng Sông Cửu Long", englishName: "Mekong Delta", region: "south",   position: { x: 50, y: 92 }, unitId: "u0" },
  { id: "saigon",   name: "Sài Gòn",                  englishName: "Saigon",        region: "south",   position: { x: 60, y: 84 }, unitId: "u1" },
  { id: "dalat",    name: "Đà Lạt",                   englishName: "Đà Lạt",        region: "south",   position: { x: 67, y: 74 }, unitId: "u2" },
  { id: "hoian",    name: "Hội An",                   englishName: "Hội An",        region: "central", position: { x: 76, y: 60 }, unitId: "u3" },
  { id: "danang",   name: "Đà Nẵng",                  englishName: "Đà Nẵng",       region: "central", position: { x: 75, y: 55 }, unitId: "u4" },
  { id: "hue",      name: "Huế",                      englishName: "Huế",           region: "central", position: { x: 70, y: 48 }, unitId: "u5" },
  { id: "ninhbinh", name: "Ninh Bình",                englishName: "Ninh Bình",     region: "north",   position: { x: 53, y: 30 }, unitId: "u6" },
  { id: "halong",   name: "Hạ Long",                  englishName: "Hạ Long Bay",   region: "north",   position: { x: 65, y: 22 }, unitId: "u7" },
  { id: "hanoi",    name: "Hà Nội",                   englishName: "Hà Nội",        region: "north",   position: { x: 50, y: 22 }, unitId: "u8" },
];

export const UNIT_BY_ID = Object.fromEntries(UNITS.map((u) => [u.id, u]));
export const LESSON_BY_ID = Object.fromEntries(
  UNITS.flatMap((u) => u.lessons.map((l) => [l.id, l] as const))
);

export function getLesson(id: string) {
  return LESSON_BY_ID[id];
}
export function getUnit(id: string) {
  return UNIT_BY_ID[id];
}
