import type { City, Unit } from "@/lib/game/types";

/**
 * Southern-dialect curriculum seed.
 * Phase 1 ships Unit 0 + Unit 1; Phase 2+ adds Units 2–12.
 */

export const UNITS: Unit[] = [
  {
    id: "u0",
    order: 0,
    title: "Âm Thanh",
    titleEnglish: "Sounds",
    theme: "sounds",
    city: "mekong",
    description: "Meet the 6 written tones (5 spoken in the South), Vietnamese vowels, and your first words.",
    lessons: [
      {
        id: "u0-l1",
        unitId: "u0",
        order: 1,
        title: "Năm Thanh",
        titleEnglish: "The Five Spoken Tones",
        xpReward: 30,
        exercises: [
          {
            id: "u0-l1-e1",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            promptEnglish: "Listen carefully — the tone changes the meaning",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "ma",
            correctTone: "ngang",
          },
          {
            id: "u0-l1-e2",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "má",
            correctTone: "sac",
          },
          {
            id: "u0-l1-e3",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "mà",
            correctTone: "huyen",
          },
          {
            id: "u0-l1-e4",
            kind: "tone-match",
            prompt: "Listen and tap the tone you hear",
            trainsStat: "thanhDieu",
            baseSyllable: "ma",
            audioText: "mạ",
            correctTone: "nang",
          },
          {
            id: "u0-l1-e5",
            kind: "translate",
            prompt: "Which one means \"mother\" (Southern)?",
            trainsStat: "tuVung",
            direction: "vi-to-en",
            source: "má",
            options: ["ghost", "but", "mother", "tomb"],
            correct: 2,
          },
        ],
      },
      {
        id: "u0-l2",
        unitId: "u0",
        order: 2,
        title: "Bảng Chữ Cái",
        titleEnglish: "The Alphabet",
        xpReward: 30,
        exercises: [
          {
            id: "u0-l2-e1",
            kind: "listen",
            prompt: "Tap the syllable you hear",
            trainsStat: "thinh",
            audioText: "đi",
            options: ["đi", "ti", "thi", "chi"],
            correct: 0,
          },
          {
            id: "u0-l2-e2",
            kind: "listen",
            prompt: "Tap the syllable you hear",
            trainsStat: "thinh",
            audioText: "nghe",
            options: ["nghe", "ne", "ne̲", "ngê"],
            correct: 0,
          },
          {
            id: "u0-l2-e3",
            kind: "listen",
            prompt: "Tap the syllable you hear",
            trainsStat: "thinh",
            audioText: "phở",
            options: ["pho", "phở", "phổ", "pha"],
            correct: 1,
          },
          {
            id: "u0-l2-e4",
            kind: "translate",
            prompt: "Which sound does the letter Đ make?",
            trainsStat: "van",
            direction: "vi-to-en",
            source: "đ",
            options: ["like 'd' in 'do'", "like 'th' in 'this'", "like 'z' in 'zoo'", "like 'y' in 'yes'"],
            correct: 0,
          },
        ],
      },
      {
        id: "u0-l3",
        unitId: "u0",
        order: 3,
        title: "Từ Đầu Tiên",
        titleEnglish: "First Words",
        xpReward: 40,
        exercises: [
          {
            id: "u0-l3-e1",
            kind: "translate",
            prompt: "How do you say \"hello\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "hello",
            options: ["chào", "cảm ơn", "tạm biệt", "xin lỗi"],
            correct: 0,
          },
          {
            id: "u0-l3-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "cảm ơn",
            options: ["cảm ơn", "không", "chào", "xin lỗi"],
            correct: 0,
          },
          {
            id: "u0-l3-e3",
            kind: "translate",
            prompt: "What does \"cảm ơn\" mean?",
            trainsStat: "tuVung",
            direction: "vi-to-en",
            source: "cảm ơn",
            options: ["sorry", "hello", "thank you", "goodbye"],
            correct: 2,
          },
          {
            id: "u0-l3-e4",
            kind: "tone-match",
            prompt: "What tone is on \"chào\"?",
            trainsStat: "thanhDieu",
            baseSyllable: "chao",
            audioText: "chào",
            correctTone: "huyen",
          },
          {
            id: "u0-l3-e5",
            kind: "translate",
            prompt: "How do you say \"goodbye\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "goodbye",
            options: ["xin chào", "tạm biệt", "không sao", "cảm ơn"],
            correct: 1,
          },
        ],
      },
    ],
  },
  {
    id: "u1",
    order: 1,
    title: "Xin Chào",
    titleEnglish: "Greetings",
    theme: "greetings",
    city: "saigon",
    description: "Greet, introduce yourself, and meet someone in Sài Gòn.",
    lessons: [
      {
        id: "u1-l1",
        unitId: "u1",
        order: 1,
        title: "Chào Hỏi",
        titleEnglish: "Saying Hello",
        xpReward: 40,
        exercises: [
          {
            id: "u1-l1-e1",
            kind: "translate",
            prompt: "How do you say \"hello\" politely (to someone older)?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "hello (polite)",
            options: ["chào bạn", "xin chào", "ê", "ơi"],
            correct: 1,
          },
          {
            id: "u1-l1-e2",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "xin chào",
            options: ["xin chào", "cảm ơn", "tạm biệt", "không sao"],
            correct: 0,
          },
          {
            id: "u1-l1-e3",
            kind: "translate",
            prompt: "What does \"chào em\" mean?",
            trainsStat: "tuVung",
            promptEnglish: "Em = younger person",
            direction: "vi-to-en",
            source: "chào em",
            options: ["hi (to younger person)", "thank you younger sibling", "see you later", "good morning"],
            correct: 0,
          },
          {
            id: "u1-l1-e4",
            kind: "tone-match",
            prompt: "Tap the tone on \"chào\"",
            trainsStat: "thanhDieu",
            baseSyllable: "chao",
            audioText: "chào",
            correctTone: "huyen",
          },
        ],
      },
      {
        id: "u1-l2",
        unitId: "u1",
        order: 2,
        title: "Tên Của Bạn",
        titleEnglish: "Your Name",
        xpReward: 40,
        exercises: [
          {
            id: "u1-l2-e1",
            kind: "translate",
            prompt: "How do you ask \"What's your name?\" (to a friend)",
            trainsStat: "nguPhap",
            direction: "en-to-vi",
            source: "what's your name?",
            options: ["bạn tên gì?", "tôi là ai?", "bạn ở đâu?", "bao nhiêu tuổi?"],
            correct: 0,
          },
          {
            id: "u1-l2-e2",
            kind: "translate",
            prompt: "Translate: \"My name is Mai\"",
            trainsStat: "but",
            direction: "en-to-vi",
            source: "my name is Mai",
            options: ["tôi tên Mai", "bạn tên Mai", "Mai là tôi", "tôi là Mai gì"],
            correct: 0,
          },
          {
            id: "u1-l2-e3",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "tôi tên là Nam",
            options: ["tôi tên là Nam", "tôi tên là Nga", "tôi tên là Lan", "tôi tên là Hà"],
            correct: 0,
          },
          {
            id: "u1-l2-e4",
            kind: "translate",
            prompt: "What does \"tên\" mean?",
            trainsStat: "tuVung",
            direction: "vi-to-en",
            source: "tên",
            options: ["age", "name", "home", "you"],
            correct: 1,
          },
        ],
      },
      {
        id: "u1-l3",
        unitId: "u1",
        order: 3,
        title: "Lịch Sự",
        titleEnglish: "Politeness",
        xpReward: 50,
        exercises: [
          {
            id: "u1-l3-e1",
            kind: "translate",
            prompt: "How do you say \"thank you\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "thank you",
            options: ["xin lỗi", "cảm ơn", "không có gì", "vui lòng"],
            correct: 1,
          },
          {
            id: "u1-l3-e2",
            kind: "translate",
            prompt: "How do you say \"sorry\"?",
            trainsStat: "tuVung",
            direction: "en-to-vi",
            source: "sorry",
            options: ["cảm ơn", "xin chào", "xin lỗi", "không sao"],
            correct: 2,
          },
          {
            id: "u1-l3-e3",
            kind: "translate",
            prompt: "What does \"không có gì\" mean?",
            trainsStat: "tuVung",
            promptEnglish: "Common reply",
            direction: "vi-to-en",
            source: "không có gì",
            options: ["I don't know", "you're welcome / no problem", "I'm sorry", "see you later"],
            correct: 1,
          },
          {
            id: "u1-l3-e4",
            kind: "listen",
            prompt: "Tap what you hear",
            trainsStat: "thinh",
            audioText: "rất vui được gặp bạn",
            options: ["rất vui được gặp bạn", "tôi không biết bạn", "hẹn gặp lại bạn", "cảm ơn nhiều bạn"],
            correct: 0,
          },
          {
            id: "u1-l3-e5",
            kind: "translate",
            prompt: "Translate: \"Nice to meet you\"",
            trainsStat: "but",
            direction: "en-to-vi",
            source: "nice to meet you",
            options: ["chào tạm biệt", "rất vui được gặp bạn", "cảm ơn rất nhiều", "xin lỗi nhiều"],
            correct: 1,
          },
        ],
      },
    ],
  },
];

/** 9 cities along the South-to-North journey, with SVG positions on a stylized Vietnam map. */
export const CITIES: City[] = [
  { id: "mekong",   name: "Đồng Bằng Sông Cửu Long", englishName: "Mekong Delta", region: "south",   position: { x: 50, y: 92 }, unitId: "u0" },
  { id: "saigon",   name: "Sài Gòn",                  englishName: "Saigon",        region: "south",   position: { x: 60, y: 84 }, unitId: "u1" },
  { id: "dalat",    name: "Đà Lạt",                   englishName: "Đà Lạt",        region: "south",   position: { x: 67, y: 74 }, unitId: "u2" },
  { id: "hoian",    name: "Hội An",                   englishName: "Hội An",        region: "central", position: { x: 76, y: 60 }, unitId: "u3" },
  { id: "danang",   name: "Đà Nẵng",                  englishName: "Đà Nẵng",       region: "central", position: { x: 75, y: 55 }, unitId: "u4" },
  { id: "hue",      name: "Huế",                      englishName: "Huế",           region: "central", position: { x: 70, y: 48 }, unitId: "u5" },
  { id: "ninhbinh", name: "Ninh Bình",                englishName: "Ninh Bình",     region: "north",   position: { x: 53, y: 30 }, unitId: "u6" },
  { id: "halong",   name: "Hạ Long",                  englishName: "Hạ Long Bay",   region: "north",   position: { x: 65, y: 22 }, unitId: "u7" },
  { id: "hanoi",    name: "Hà Nội",                   englishName: "Hà Nội",        region: "north",   position: { x: 50, y: 22 }, unitId: "u8" },
];

export const UNIT_BY_ID = Object.fromEntries(UNITS.map((u) => [u.id, u]));
export const LESSON_BY_ID = Object.fromEntries(
  UNITS.flatMap((u) => u.lessons.map((l) => [l.id, l] as const))
);

export function getLesson(id: string) {
  return LESSON_BY_ID[id];
}
export function getUnit(id: string) {
  return UNIT_BY_ID[id];
}
